//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGestionEval
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_gestionEntities : DbContext
    {
        public bd_gestionEntities()
            : base("name=bd_gestionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspnetroles> aspnetroles { get; set; }
        public virtual DbSet<aspnetuserclaims> aspnetuserclaims { get; set; }
        public virtual DbSet<aspnetuserlogins> aspnetuserlogins { get; set; }
        public virtual DbSet<aspnetusers> aspnetusers { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<collaborateur> collaborateur { get; set; }
        public virtual DbSet<evaluation> evaluation { get; set; }
        public virtual DbSet<famillecritere> famillecritere { get; set; }
        public virtual DbSet<fonction> fonction { get; set; }
        public virtual DbSet<projet> projet { get; set; }
        public virtual DbSet<variable> variable { get; set; }
        public virtual DbSet<critere> critere { get; set; }
        public virtual DbSet<tache> tache { get; set; }
    }
}
