//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGestionEval
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.projet = new HashSet<projet>();
        }
    
        public int IDCLIENT { get; set; }
        public string ABREVIATION { get; set; }
    
        public virtual ICollection<projet> projet { get; set; }
    }
}
