//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGestionEval
{
    using System;
    using System.Collections.Generic;
    
    public partial class collaborateur
    {
        public collaborateur()
        {
            this.evaluation = new HashSet<evaluation>();
            this.tache = new HashSet<tache>();
            this.evaluation1 = new HashSet<evaluation>();
            this.projet = new HashSet<projet>();
        }
    
        public int IDCOLLABORATEUR { get; set; }
        public int IDFONCTION { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public byte[] IMAGE { get; set; }
        public bool FLAGEVAL { get; set; }
        public string TYPECOLLABORATEUR { get; set; }
        public System.DateTime DATEEMBAUCHE { get; set; }
        public Nullable<System.DateTime> DATESORTIE { get; set; }
        public string IdUser { get; set; }
    
        public virtual aspnetusers aspnetusers { get; set; }
        public virtual fonction fonction { get; set; }
        public virtual ICollection<evaluation> evaluation { get; set; }
        public virtual ICollection<tache> tache { get; set; }
        public virtual ICollection<evaluation> evaluation1 { get; set; }
        public virtual ICollection<projet> projet { get; set; }
    }
}
