//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGestionEval
{
    using System;
    using System.Collections.Generic;
    
    public partial class projet
    {
        public projet()
        {
            this.collaborateur = new HashSet<collaborateur>();
            this.tache = new HashSet<tache>();
        }
    
        public int IDPROJET { get; set; }
        public int IDCLIENT { get; set; }
        public string NOMPROJET { get; set; }
        public Nullable<System.DateTime> DATEDEBUT { get; set; }
        public Nullable<System.DateTime> DATEFIN { get; set; }
        public Nullable<int> TYPE { get; set; }
        public bool FLAGTYPE { get; set; }
    
        public virtual client client { get; set; }
        public virtual ICollection<collaborateur> collaborateur { get; set; }
        public virtual ICollection<tache> tache { get; set; }
    }
}
